// buildBSC.mjs — generate bscCatalog.js from HYG v4.1 (pre-filtered to mag≤5.0)
// Usage: node buildBSC.mjs /tmp/hyg_bright.csv
// Output: bscCatalog.js in the same directory as this script
import { createReadStream } from 'fs';
import { createInterface } from 'readline';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dir = dirname(fileURLToPath(import.meta.url));
const csvPath = process.argv[2] || '/tmp/hyg_bright.csv';

// Existing star IDs in ZODIAC_STARS and ECLIPTIC_GUIDE_STARS — skip duplicates
const SKIP_IDS = new Set([
  'aldebaran','antares','spica','regulus','pollux','castor','graffias',
  'deneb_algedi','sadalsuud','zubenelgenubi','zubeneschamali','acubens',
  'denebola','alcyone','ain','asellus_aus','eta_psc','vindemiatrix',
]);

function makeId(proper, bayer, flam, con, hr) {
  if (proper && proper.trim()) {
    return proper.trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
  }
  if (bayer && bayer.trim()) {
    const b = bayer.trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
    return b;
  }
  if (flam && flam.trim() && con && con.trim()) {
    return flam.trim() + '_' + con.trim().toLowerCase();
  }
  if (hr && hr.trim()) return 'hr' + hr.trim();
  return null;
}

function makeName(proper, bayer, flam, con, hr) {
  if (proper && proper.trim()) return proper.trim();
  if (bayer && bayer.trim()) return bayer.trim();
  if (flam && flam.trim() && con && con.trim()) return flam.trim() + ' ' + con.trim();
  if (hr && hr.trim()) return 'HR ' + hr.trim();
  return '?';
}

function stripQuotes(s) {
  if (!s) return s;
  return s.replace(/^"|"$/g, '').trim();
}

const rl = createInterface({ input: createReadStream(csvPath) });
const stars = [];
let header = null;
const seenIds = new Set(SKIP_IDS);

rl.on('line', (line) => {
  if (!line.trim()) return;
  const cols = line.split(',');
  if (!header) { header = cols; return; }

  // cols: id=0, hip=1, hd=2, hr=3, gl=4, bf=5, proper=6, ra=7, dec=8, dist=9,
  //       pmra=10, pmdec=11, rv=12, mag=13, absmag=14, spect=15, ci=16, x=17,
  //       y=18, z=19, vx=20, vy=21, vz=22, rarad=23, decrad=24, pmrarad=25,
  //       pmdecrad=26, bayer=27, flam=28, con=29
  const hr   = stripQuotes(cols[3]);
  const proper = stripQuotes(cols[6]);
  const ra   = stripQuotes(cols[7]);
  const dec  = stripQuotes(cols[8]);
  const mag  = stripQuotes(cols[13]);
  const bayer = stripQuotes(cols[27]);
  const flam  = stripQuotes(cols[28]);
  const con   = stripQuotes(cols[29]);

  const magF = parseFloat(mag);
  if (isNaN(magF) || magF > 5.0) return;

  const raF = parseFloat(ra);
  const decF = parseFloat(dec);
  if (isNaN(raF) || isNaN(decF)) return;

  // HYG ra is already in decimal hours (0-24)
  const id = makeId(proper, bayer, flam, con, hr);
  if (!id || seenIds.has(id)) return;
  seenIds.add(id);

  const name = makeName(proper, bayer, flam, con, hr);

  stars.push({ id, name, raH: +raF.toFixed(6), decD: +decF.toFixed(4), mag: +magF.toFixed(2) });
});

rl.on('close', () => {
  // Sort brightest first
  stars.sort((a, b) => a.mag - b.mag);

  const lines = stars.map(s =>
    `  { id: '${s.id}', name: '${s.name.replace(/'/g, "\\'")}', raH: ${s.raH.toFixed(4)}, decD: ${s.decD.toFixed(4)}, mag: ${s.mag.toFixed(2)} },`
  );

  const out = `// bscCatalog.js — stars with visual magnitude ≤ 5.0 from HYG v4.1 / BSC5
// Generated by buildBSC.mjs.  J2000.0 coordinates.  ${stars.length} entries.
// RA in decimal hours, Dec in decimal degrees.
// Stars already in ZODIAC_STARS or ECLIPTIC_GUIDE_STARS are excluded (no duplicate IDs).

export const BSC_STARS = [
${lines.join('\n')}
];
`;

  const outPath = join(__dir, 'bscCatalog.js');
  writeFileSync(outPath, out, 'utf8');
  console.log(`Written ${stars.length} stars to ${outPath}`);
});
