#!/usr/bin/env node
// buildEpiTables.mjs — generate ephemerisEpiTables.js
//
// Daily geocentric RA/Dec at 00:00 UTC.
// Usage: node buildEpiTables.mjs [yearFrom] [yearTo]
// Default: 1900–2100

import { writeFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { bodyGeocentric } from './ephemerisEpicycle.js';
import { DEG } from './epiCore.js';

const __dir = dirname(fileURLToPath(import.meta.url));
const YEAR_FROM = parseInt(process.argv[2] ?? '1900', 10);
const YEAR_TO   = parseInt(process.argv[3] ?? '2100', 10);
const BODIES    = ['sun','moon','mercury','venus','mars','jupiter','saturn','uranus','neptune'];
const MS_PER_DAY = 86400000;

const isLeap = y => (y % 4 === 0 && y % 100 !== 0) || y % 400 === 0;
const daysInYear = y => isLeap(y) ? 366 : 365;

function encode(r) {
  if (!r || !Number.isFinite(r.ra) || !Number.isFinite(r.dec)) return [NaN, NaN];
  const raDeg = ((r.ra * DEG) % 360 + 360) % 360;
  return [raDeg * 240, r.dec * DEG * 3600];
}

const totalYears = YEAR_TO - YEAR_FROM + 1;
const totalDays  = Array.from({length:totalYears},(_,i)=>daysInYear(YEAR_FROM+i)).reduce((a,b)=>a+b,0);
console.log(`\nEpiTable generator  ${YEAR_FROM}–${YEAR_TO}  (${totalYears} years, ${totalDays.toLocaleString()} days)\n`);

const result = {
  meta: {
    source: 'Custom epicycle ephemeris — ephemerisEpicycle.js',
    note: 'Pure Keplerian geocentric. No perturbation terms.',
    generatedAt: new Date().toISOString(),
    yearMin: YEAR_FROM, yearMax: YEAR_TO, bodies: BODIES,
    columns: ['raSec (RA seconds of time 0-86400)', 'decArcsec (signed arcseconds)'],
  },
};
for (const b of BODIES) result[b] = {};

const t0 = Date.now();

for (let year = YEAR_FROM; year <= YEAR_TO; year++) {
  const days = daysInYear(year);
  const yearStartMs = Date.UTC(year, 0, 1, 0, 0, 0);
  const arrs = {};
  for (const b of BODIES) arrs[b] = new Array(days * 2);

  for (let d = 0; d < days; d++) {
    const date = new Date(yearStartMs + d * MS_PER_DAY);
    for (const b of BODIES) {
      const [rs, ds] = encode(bodyGeocentric(b, date));
      arrs[b][d*2]   = rs;
      arrs[b][d*2+1] = ds;
    }
  }
  for (const b of BODIES) result[b][year] = arrs[b];

  const done = year - YEAR_FROM + 1;
  const pct  = (done/totalYears*100).toFixed(0).padStart(3);
  const bar  = '█'.repeat(Math.floor(done/totalYears*30)).padEnd(30,'░');
  process.stdout.write(`  [${bar}] ${pct}%  ${year}  ${((Date.now()-t0)/1000).toFixed(1)}s  \r`);
}

console.log(`\n\nDone in ${((Date.now()-t0)/1000).toFixed(1)}s`);

const outPath = join(__dir, 'ephemerisEpiTables.js');
const header = `// ephemerisEpiTables.js — auto-generated by buildEpiTables.mjs.
// Regenerate: node buildEpiTables.mjs ${YEAR_FROM} ${YEAR_TO}
// Source: ephemerisEpicycle.js (pure Keplerian geocentric, J2000 epoch).
// Coverage: ${YEAR_FROM}–${YEAR_TO}. Bodies: ${BODIES.join(', ')}.
// Format: EPITABLES[body][year] = [raSec0, decArcsec0, raSec1, decArcsec1, …]
// One pair per day at 00:00 UTC. raSec = RA in seconds of time (0–86400).
// Format matches the epicycle pipeline output — consumed by ephemerisEpiTablesRuntime.js.
// Accuracy: Sun ~0.5° Moon ~1° Venus ~1-2° Mars ~5-10° Jupiter ~7-10°

`;
writeFileSync(outPath, header + `export const EPITABLES = ${JSON.stringify(result)};\n`);
const sizeMB = (statSync(outPath).size / 1024 / 1024).toFixed(1);
console.log(`Wrote ${outPath}  (${sizeMB} MB)`);
